* Fixing the issue:  Assets/_DebugToolsAlMartson/EditorTimeExternalAssetTools/DTValidator/Icons/DTValidatorIcons.cs(46,26): error CS0103: The name 'Texture2DUtil' does not exist in the current context
By commiting + push the files